### ISSUE TITLE
Add Each command to documentation

### ISSUE THREAD

**Issue by josephmancuso** [mansam/validator.py#13]
You have an Each test in this repo and an Each class but i don't see anything documented for it. Is there a reason for this?

**Comment by mansam** [comment]
Hey, thanks for the report. I'll fix the gap in the docs as soon as I can.

**Comment by josephmancuso** [comment]
awesome. Thanks :) great package. It's the default for the Masonite framework btw :)

**Comment by mansam** [comment]
Hey @josephmancuso , I just updated the documentation and pushed a new release to PyPI. I'm glad you like the package and I'm thrilled that you're finding it useful :)

**Comment by josephmancuso** [comment]
awesome! did you happen to get my email?

**Comment by mansam** [comment]
@josephmancuso I did, just responded and joined your slack ;)
