### ISSUE TITLE
The package's page on pypi lists its license as "LICENSE"

### ISSUE THREAD

**Issue by eli-b** [mansam/validator.py#6]
See the bottom of https://pypi.python.org/pypi/validator.py.

**Comment by mansam** [comment]
You're absolutely right, thanks for catching this oversight.

**Comment by eli-b** [comment]
The PKG-INFO file in the 1.2.4 egg still says "License: UNKNOWN".
Sorry I'm being so technical, but I have automated tests that use this data to make sure I only use FOSS packages, and UNKNOWN isn't a white-listed license there.

**Comment by mansam** [comment]
I apologize, when I added the trove classifiers I added the one for MIT, and then removed the `license` field from `setup.py` since the documentation suggested that it was optional if an appropriate classifier was present. I will re-add the `license` field so that your tests pass. :)

**Comment by mansam** [comment]
I cut a new release to fix that regression. Sorry for breaking your tests!

**Comment by eli-b** [comment]
Yay! Thanks again for being so responsive.
