### ISSUE TITLE
The package's page on pypi doesn't link to this repository

### ISSUE THREAD

**Issue by eli-b** [mansam/validator.py#7]
This might be intentional, but at the bottom of https://pypi.python.org/pypi/validator.py, the package's homepage is the pypi page.
This makes it more difficult to participate in the package's development.

**Comment by mansam** [comment]
You're absolutely right, thanks for catching this oversight. I've just made a commit that fixes this and the other issue you reported, and pushed a new release to PyPI (1.2.2) since they were directly affecting how the project appeared there.
