### ISSUE TITLE
caniusepython3.com lists validator.py as a blocker for python 3 migration

### ISSUE THREAD

**Issue by eli-b** [mansam/validator.py#8]
See https://caniusepython3.com/project/validator.py.

As the the 3.4 tests pass (https://travis-ci.org/mansam/validator.py), maybe it's just a matter of updating some package metadata again.

Also, what about python 3.5?

**Comment by mansam** [comment]
Certainly sounds like a metadata problem-- it's 2/3 compatible and tested from 2.6 through 3.4 (and should work on 3.5, though I'm going to add another line to the the travis file to explicitly test that).

**Comment by mansam** [comment]
Thanks again for your thorough reporting. I've updated the package classifiers, and the travis test matrix now includes 3.5. I've cut a new release for PyPI, and now `caniusepython3` shows the all clear.
